#!/usr/bin/env python3

# Script 4 parsing OpenAPI3 schema (in project-specific format, for ex. modelType)
# To Newman compatible view
import fileinput
import json
import re

def unpack_schema(common, response_schema, name):
    if 'modelType' in response_schema and response_schema['modelType'] == 'ref':
        ref = response_schema['$ref']
        parse = re.match(r'#components/schemas/(.+)', ref)
        response_schema = common['components']['schemas'][parse.group(1)]
        return unpack_schema(common, response_schema, name)
    elif 'oneOf' in response_schema:
        responses_mul = []
        for one_response in response_schema['oneOf']:
            responses_mul.append(unpack_schema(common, one_response, name))
        return {'oneOf': responses_mul}
    elif response_schema['modelType'] == 'schema' and response_schema['type'] == 'object' or response_schema['type'] == 'array':
        return unpack_properties(common, response_schema, name)
    elif response_schema['modelType'] == 'schema' and (response_schema['type'] == 'string'  or
                                                       response_schema['type'] == 'integer' or
                                                       response_schema['type'] == 'boolean' or
                                                       response_schema['type'] == 'number'  or
                                                       response_schema['type'] == 'void'):
        if 'nullable' in response_schema and response_schema['nullable']:
            response_schema['type'] = [response_schema['type'], 'null']
        return response_schema
    elif response_schema['modelType'] == 'schema' and isinstance(response_schema['type'], list):
        return response_schema #уже изменили по ссылке
    else:
        raise Exception('Wrong type {0} of schema in {1}'.format(response_schema['modelType'], name))

def unpack_properties(common, response_schema, name):
    if response_schema['type'] == 'object':
        for field in response_schema['properties']:
            field_obj = response_schema['properties'][field]
            response_schema['properties'][field] = unpack_schema(common, response_schema['properties'][field], name)
    elif response_schema['type'] == 'array':
        response_schema['items'] = unpack_schema(common, response_schema['items'], name)
    return response_schema

data = input()
schema = json.loads(data.encode('utf-8'))

results = []
for path in schema['paths'].keys():
    for method in schema['paths'][path]:
        name = schema['paths'][path][method]['operationId']
        responses = schema['paths'][path][method]['responses']
        if not '200' in responses or not 'application/json' in responses['200']['content']:
        	continue
        response_schema = responses['200']['content']['application/json']['schema']
        parsed_schema = unpack_schema(schema, response_schema, name)
        results.append([name, parsed_schema])

for r in results:
    print(r[0])
    print(r[1])
    print()
